export const  ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const  ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const  ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const  DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const  DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const  DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const  GET_POST_LIST_REQUEST = 'GET_POST_LIST_REQUEST';
export const  GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const  GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE';