export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const  INIT_INGREDIENT_REQUEST = 'INIT_INGREDIENT_REQUEST';
export const  INIT_INGREDIENT_SUCCESS = 'INIT_INGREDIENT_SUCCESS';
export const  INIT_INGREDIENT_FAILURE = 'INIT_INGREDIENT_FAILURE';

export const  GET_ORDER_LIST_REQUEST = 'GET_ORDER_LIST_REQUEST';
export const  GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const  GET_ORDER_LIST_FAILURE = 'GET_ORDER_LIST_FAILURE';